import Head from 'next/head'
import React from 'react'
import CardBox from '../components/CardBox'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <div className="grid grid-cols-3 gap-5 max-w-5xl mx-auto">
      <CardBox title="Truthseekers">
        <p>Content for card 1</p>
      </CardBox>
      <CardBox title="LunaSky">
        <p>Content for card 2</p>
      </CardBox>
      <CardBox title="Niftables">
        <p>Content for card 3</p>
      </CardBox>
      <CardBox title="Truthseekers">
        <p>Content for card 1</p>
      </CardBox>
      <CardBox title="LunaSky">
        <p>Content for card 2</p>
      </CardBox>
    </div>
      </main>
    </>
  )
}
